#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2005-2007 TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.

import optparse
import sys

import comar
import zorg
from zorg.opengl import OpenGL
from zorg.utils import parseMode
from zorg.config import ZorgConfig

zorg_info = " Xorg AutoConfiguration tool"

class OUT:
    def __init__(self, colorout):
        if colorout:
            self.NORMAL = '\x1b[37;0m'
            self.BOLD = '\x1b[37;01m'
            self.MARK = '\x1b[36;01m'
            self.WARN = '\x1b[35m'
            self.WARNMSG = '\x1b[35;01m'
            self.ERROR = '\x1b[31m'
            self.ERRORMSG = '\x1b[31;01m'
        else:
            self.NORMAL = ''
            self.BOLD = ''
            self.MARK = ''
            self.WARN = ''
            self.WARNMSG = ''
            self.ERROR = ''
            self.ERRORMSG = ''

        self.type_sect = "%s-> " % self.MARK
        self.type_info = "%s   " % self.NORMAL
        self.type_warn = "%sWW " % self.WARN
        self.type_error  = "%sEE " % self.ERROR

    def _write(self, type, msg):
        print "%s %s%s" % (type, msg, self.NORMAL)

    def sect(self, msg):
        self._write(self.type_sect, "%s%s" % (self.BOLD, msg))

    def info(self, msg):
        self._write(self.type_info, msg)

    def warn(self, msg):
        self._write(self.type_warn, "%s%s" % (self.WARNMSG, msg))

    def error(self, msg):
        self._write(self.type_error, "%s%s" % (self.ERRORMSG, msg))

def safe():
    link.Xorg.Display.safeConfigure()

def probe(opts):
    if opts.mode:
        res, depth = parseMode(opts.mode)
        if not res:
            out.error("Mode is not supported or not valid: %s" % opts.mode)
            return

    out.sect("Probing devices for a single head configuration...")
    link.Xorg.Display.autoConfigure()
    reply = link.read_cmd()
    if reply.command == "result":
        out.info("Automatic configuration done.")
    else:
        out.error(reply.data)
        return

    if opts.mode:
        setMode(opts)

def setMode(opts):
    z = ZorgConfig()
    scr = z.getScreen(0)
    if not scr:
        out.error("Could not get screen info")
        return
    
    out.sect("Setting mode to %s" % opts.mode)

    res = opts.mode.split("-")[0]
    if res in scr.monitor.res:
        pass
    elif opts.force:
        out.warn("Forcing unsupported mode: %s" % opts.mode)
    else:
        out.error("Mode is not supported: %s" % opts.mode)
        return

    link.Xorg.Display.setScreen(screenNumber="0", cardId=scr.device.id,
                                monitorId=scr.monitor.id, mode=opts.mode)

    reply = link.read_cmd()
    if reply.command == "fail":
        out.error(reply.data)

def setDriver(driver):
    z = ZorgConfig()
    scr = z.getScreen(0)
    if not scr:
        out.error("Could not get screen info")
        return

    out.sect("Setting card driver to %s" % driver)
    opts = "driver=%s" % driver
    link.Xorg.Display.setCardOptions(cardId=scr.device.id, options=opts)
    reply = link.read_cmd()
    if reply.command == "fail":
        out.error(reply.data)
        
    updateOpenGL(None, False)

def info():
    z = ZorgConfig()

    cards = {}
    monitors = {}

    for card in z.cards():
        cards[card.id] = card.boardName

        if card.busId:
            out.sect("Configured a video card on %s bus %s, device %s, function %s"
                    % tuple(card.busId.split(":")))
        else:
            out.sect("Configured a failsafe video driver")
        out.info("  PCI ID = %s:%s" % (card.vendorId, card.deviceId))
        out.info("  Vendor = %s" % card.vendorName)
        out.info("  Device = %s" % card.boardName)
        out.info("  Driver = %s" % card.driver)
        out.info("")
        out.info("  Monitors connected to this device:")

        if not card.monitors:
            out.error("    Could not find any configured monitors for this device")
            continue

        for mon in card.monitors:
            monitors[mon.id] = mon.modelname
            out.info("    Vendor                = %s" % mon.vendorname)
            out.info("    Model                 = %s" % mon.modelname)
            out.info("    Supported resolutions = %s" % ",".join(mon.res))
            out.info("")

    for n in 0, 1:
        scr = z.getScreen(n)
        out.sect("Screen %s properties:" % n)

        if not scr:
            out.warn("  Not configured")
            continue

        out.info("  Video card  = %s" % cards[scr.device.id])
        out.info("  Monitor     = %s" % monitors[scr.monitor.id])
        out.info("  Resolution  = %s" % scr.res)
        out.info("  Color depth = %s" % scr.depth)
        out.info("")

    o = OpenGL()
    out.info("")
    out.sect("Current OpenGL implementation is %s" % o.current)

def updateOpenGL(impl, headers):
    if not impl:
        z = ZorgConfig()
        scr = z.getScreen(0)
        if not scr:
            out.error("Could not get screen info")
            return

        from zorg.probe import driver2opengl
        impl = driver2opengl(scr.device.driver)

    out.sect("Switching to %s OpenGL implementation" % impl)
    link.Xorg.Display.updateOpenGL(implementation=impl,
                                   withHeaders=str(headers))
    reply = link.read_cmd()
    if reply.command == "fail":
        out.error(reply.data)


if __name__ == "__main__":
    # running from command line
    parser = optparse.OptionParser(description = "%s version %s"
                                    % (zorg_info, zorg.versionString()))

    parser.add_option("-n", "--no-color", action="store_false",
        dest="colorout", default=True,
        help="do not print colorized output")

    parser.add_option("-s", "--safe", action="store_true",
        dest="safe", default=False,
        help="setup VESA 800x600 config without probing hardware")

    parser.add_option("-p", "--probe", action="store_true",
        dest="probe", default=False,
        help="force probing all devices, even if xorg.conf exists")

    parser.add_option("-m", "--mode", action="store", type="string",
        dest="mode", default=None,
        help="use MODE given in form <width>x<height>[-<depth>] if supported")

    parser.add_option("-f", "--force", action="store_true",
        dest="force", default=False,
        help="force using the specified mode (use with caution)")

    parser.add_option("-d", "--driver", action="store", type="string",
        dest="driver", default=None,
        help="set video card driver to DRIVER")

    parser.add_option("-i", "--info", action="store_true",
        dest="info", default=False,
        help="print video, monitor and input info, no probing is done")

    parser.add_option("-g", "--update-opengl", action="store_true",
        dest="opengl", default=False,
        help="update OpenGL implementation")

    parser.add_option("-I", "--implementation", action="store", type="string",
        dest="impl", default=None,
        help="use IMPL as OpenGL implementation (used with -g)")

    parser.add_option("--with-headers", action="store_true",
        dest="headers", default=False,
        help="use headers of the selected implementation (used with -g)")

    parser.add_option("--intelfix", action="store_true",
        dest="intelfix", default=False,
        help="run Intel BIOS bug workaround")

    parser.add_option("--intellist", action="store_true",
        dest="intellist", default=False,
        help="list available BIOS modes for Intel cards")

    opts, args = parser.parse_args()
    out = OUT(opts.colorout)
    link = comar.Link()

    link.can_access("Xorg.Display.listCards")
    try:
        link.read_cmd()
    except comar.LinkClosed:
        out.error("Connection closed by COMAR daemon.")
        sys.exit(1)

    if opts.safe:
        safe()
    elif opts.probe:
        probe(opts)
    elif opts.mode or opts.driver:
        if opts.mode:
            setMode(opts)
        if opts.driver:
            setDriver(opts.driver)
    elif opts.info:
        info()
    elif opts.opengl:
        updateOpenGL(opts.impl, opts.headers)
    elif opts.intelfix:
        out.error("Not implemented yet.")
    elif opts.intellist:
        out.error("Not implemented yet.")
    else:
        parser.print_help()
